apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: chaincode-install-carrier-peer0-1
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: chaincode-install-carrier-peer0-1
  chart:
    git: https://github.com/MChorfa/blockchain-automation-framework.git
    ref: aks
    path: platforms/hyperledger-fabric/charts/install_chaincode
  values:
    metadata:
      namespace: carrier-net
      network:
        version: 2.2.0
      images:
        fabrictools: hyperledger/fabric-tools:2.2.1
        alpineutils: hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: https://vault-2.baf.thalesdigitalsolutions.ca
      authpath: devcarrier-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrier-net/users/admin 
      orderersecretprefix: secret/crypto/peerOrganizations/carrier-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretgitprivatekey: secret/credentials/carrier-net/git?git_password
      tls: false
    orderer:
      address: orderer1.supplychain-net:7050
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.0
      name: supplychain
      version: 1
      lang: golang
      maindirectory: external
      repository:
        hostname: "github.com"
        git_username: "MChorfa"
        url: github.com/MChorfa/blockchain-automation-framework.git
        branch: aks
        path: examples/chaincode/fabcar/external
      endorsementpolicies:  ''
