apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: dnd-net-ca
  namespace: dnd-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: dnd-net-ca
  chart:
    git: https://github.com/savardmario/blockchain-automation-framework.git
    ref: aks
    path: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: dnd-net
      images:
        alpineutils: hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.8
       
    server:
      name: ca
      tlsstatus: true
      admin: dnd-admin
    storage:
      storageclassname: dndsc
      storagesize: 512Mi
    vault:
      role: vault-role
      address: https://vault-2.baf.thalesdigitalsolutions.ca
      authpath: devdnd-net-auth
      secretcert: secret/crypto/peerOrganizations/dnd-net/ca?ca.dnd-net-cert.pem
      secretkey: secret/crypto/peerOrganizations/dnd-net/ca?dnd-net-CA.key
      secretadminpass: secret/credentials/dnd-net/ca/dnd?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: none
      type: peer
      external_url_suffix: develop.local.com
